<?php

/**
 * @file
 * Module file for vefl.
 */

/**
 * Helper function to rebuild views exposed form.
 */
function _vefl_change_layout_button($form, &$form_state) {
  $display = &$form_state['view']->display[$form_state['display_id']];
  $display->handler->options_submit($form, $form_state);

  //views_ui_cache_set($form_state['view']);
  $form_state['rerender'] = TRUE;
  $form_state['rebuild'] = TRUE;
}
